package com.you07.map.dao;

import com.you07.map.model.MapRoadPlaneness;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MapRoadPlanenessDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_planeness
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Delete({
        "delete from map.map_road_planeness",
        "where plan_id = #{planId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_planeness
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Insert({
        "insert into map.map_road_planeness (plan_id, plan_name, ",
        "memo)",
        "values (#{planId,jdbcType=INTEGER}, #{planName,jdbcType=VARCHAR}, ",
        "#{memo,jdbcType=VARCHAR})"
    })
    int insert(MapRoadPlaneness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_planeness
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Select({
        "select",
        "plan_id, plan_name, memo",
        "from map.map_road_planeness",
        "where plan_id = #{planId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="plan_id", property="planId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="plan_name", property="planName", jdbcType=JdbcType.VARCHAR),
        @Result(column="memo", property="memo", jdbcType=JdbcType.VARCHAR)
    })
    MapRoadPlaneness selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_planeness
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Select({
        "select",
        "plan_id, plan_name, memo",
        "from map.map_road_planeness"
    })
    @Results({
        @Result(column="plan_id", property="planId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="plan_name", property="planName", jdbcType=JdbcType.VARCHAR),
        @Result(column="memo", property="memo", jdbcType=JdbcType.VARCHAR)
    })
    List<MapRoadPlaneness> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_planeness
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Update({
        "update map.map_road_planeness",
        "set plan_name = #{planName,jdbcType=VARCHAR},",
          "memo = #{memo,jdbcType=VARCHAR}",
        "where plan_id = #{planId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MapRoadPlaneness record);
}