package com.you07.map.dao;

import com.you07.map.model.MapRoadAttribute;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MapRoadAttributeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_attribute
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Delete({
        "delete from map.map_road_attribute",
        "where roadattr_id = #{roadattrId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer roadattrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_attribute
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Insert({
        "insert into map.map_road_attribute (roadattr_id, pave_id, ",
        "plan_id, walkauth, ",
        "carauth, max_speed, ",
        "is_single, width, slope, ",
        "is_bridge, road_typeid)",
        "values (#{roadattrId,jdbcType=INTEGER}, #{paveId,jdbcType=INTEGER}, ",
        "#{planId,jdbcType=INTEGER}, #{walkauth,jdbcType=INTEGER}, ",
        "#{carauth,jdbcType=INTEGER}, #{maxSpeed,jdbcType=REAL}, ",
        "#{isSingle,jdbcType=BIT}, #{width,jdbcType=REAL}, #{slope,jdbcType=REAL}, ",
        "#{isBridge,jdbcType=BIT}, #{roadTypeid,jdbcType=INTEGER})"
    })
    int insert(MapRoadAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_attribute
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Select({
        "select",
        "roadattr_id, pave_id, plan_id, walkauth, carauth, max_speed, is_single, width, ",
        "slope, is_bridge, road_typeid",
        "from map.map_road_attribute",
        "where roadattr_id = #{roadattrId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="roadattr_id", property="roadattrId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="pave_id", property="paveId", jdbcType=JdbcType.INTEGER),
        @Result(column="plan_id", property="planId", jdbcType=JdbcType.INTEGER),
        @Result(column="walkauth", property="walkauth", jdbcType=JdbcType.INTEGER),
        @Result(column="carauth", property="carauth", jdbcType=JdbcType.INTEGER),
        @Result(column="max_speed", property="maxSpeed", jdbcType=JdbcType.REAL),
        @Result(column="is_single", property="isSingle", jdbcType=JdbcType.BIT),
        @Result(column="width", property="width", jdbcType=JdbcType.REAL),
        @Result(column="slope", property="slope", jdbcType=JdbcType.REAL),
        @Result(column="is_bridge", property="isBridge", jdbcType=JdbcType.BIT),
        @Result(column="road_typeid", property="roadTypeid", jdbcType=JdbcType.INTEGER)
    })
    MapRoadAttribute selectByPrimaryKey(Integer roadattrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_attribute
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Select({
        "select",
        "roadattr_id, pave_id, plan_id, walkauth, carauth, max_speed, is_single, width, ",
        "slope, is_bridge, road_typeid",
        "from map.map_road_attribute"
    })
    @Results({
        @Result(column="roadattr_id", property="roadattrId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="pave_id", property="paveId", jdbcType=JdbcType.INTEGER),
        @Result(column="plan_id", property="planId", jdbcType=JdbcType.INTEGER),
        @Result(column="walkauth", property="walkauth", jdbcType=JdbcType.INTEGER),
        @Result(column="carauth", property="carauth", jdbcType=JdbcType.INTEGER),
        @Result(column="max_speed", property="maxSpeed", jdbcType=JdbcType.REAL),
        @Result(column="is_single", property="isSingle", jdbcType=JdbcType.BIT),
        @Result(column="width", property="width", jdbcType=JdbcType.REAL),
        @Result(column="slope", property="slope", jdbcType=JdbcType.REAL),
        @Result(column="is_bridge", property="isBridge", jdbcType=JdbcType.BIT),
        @Result(column="road_typeid", property="roadTypeid", jdbcType=JdbcType.INTEGER)
    })
    List<MapRoadAttribute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_attribute
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Update({
        "update map.map_road_attribute",
        "set pave_id = #{paveId,jdbcType=INTEGER},",
          "plan_id = #{planId,jdbcType=INTEGER},",
          "walkauth = #{walkauth,jdbcType=INTEGER},",
          "carauth = #{carauth,jdbcType=INTEGER},",
          "max_speed = #{maxSpeed,jdbcType=REAL},",
          "is_single = #{isSingle,jdbcType=BIT},",
          "width = #{width,jdbcType=REAL},",
          "slope = #{slope,jdbcType=REAL},",
          "is_bridge = #{isBridge,jdbcType=BIT},",
          "road_typeid = #{roadTypeid,jdbcType=INTEGER}",
        "where roadattr_id = #{roadattrId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MapRoadAttribute record);
}