package com.you07.map.dao;

import com.you07.map.model.MapRoadType;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MapRoadTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_type
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Delete({
        "delete from map.map_road_type",
        "where road_typeid = #{roadTypeid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer roadTypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_type
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Insert({
        "insert into map.map_road_type (road_typeid, road_name, ",
        "memo)",
        "values (#{roadTypeid,jdbcType=INTEGER}, #{roadName,jdbcType=VARCHAR}, ",
        "#{memo,jdbcType=VARCHAR})"
    })
    int insert(MapRoadType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_type
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Select({
        "select",
        "road_typeid, road_name, memo",
        "from map.map_road_type",
        "where road_typeid = #{roadTypeid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="road_typeid", property="roadTypeid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="road_name", property="roadName", jdbcType=JdbcType.VARCHAR),
        @Result(column="memo", property="memo", jdbcType=JdbcType.VARCHAR)
    })
    MapRoadType selectByPrimaryKey(Integer roadTypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_type
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Select({
        "select",
        "road_typeid, road_name, memo",
        "from map.map_road_type"
    })
    @Results({
        @Result(column="road_typeid", property="roadTypeid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="road_name", property="roadName", jdbcType=JdbcType.VARCHAR),
        @Result(column="memo", property="memo", jdbcType=JdbcType.VARCHAR)
    })
    List<MapRoadType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map.map_road_type
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @Update({
        "update map.map_road_type",
        "set road_name = #{roadName,jdbcType=VARCHAR},",
          "memo = #{memo,jdbcType=VARCHAR}",
        "where road_typeid = #{roadTypeid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MapRoadType record);
}