server:
  port: 8081
  undertow:
    io-threads: 4
    worker-threads: 32
    buffer-size: 2048
    direct-buffers: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

druid:
  type: com.alibaba.druid.pool.DruidDataSource
  postgresdefault:
    dirver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.4.241:5432/vtpl_plus
    username: postgres
    password: lqkj007
  postgresgis:
    dirver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://202.196.16.81:5407/hngydx
    username: postgres
    password: Lqkj!@#456
  postgres-eas:
    dirver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://202.196.16.81:5407/CMCCI
    username: postgres
    password: Lqkj!@#456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.you07.util.datatype

pagehelper:
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
  helper-dialect: PostgreSQL
mapper:
  mappers: BaseDao
  not-empty: false
logging:
  config: classpath:log4j2.xml
  level:
    com.you07.vtp.dao: debug
    com.you07.eas.dao: debug
    com.you07.map.dap: debug



#请求认证的接口地址
oauth:
  client-id: cmccr-guest
  client-secret: cmccr-guest
  grant-type: client_credentials
  token: https://testgis.you07.com/cmccr-server/oauth/token