package com.you07.map.model;

public class MapRoadType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_type.road_typeid
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Integer roadTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_type.road_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private String roadName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_type.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_type.road_typeid
     *
     * @return the value of map.map_road_type.road_typeid
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getRoadTypeid() {
        return roadTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_type.road_typeid
     *
     * @param roadTypeid the value for map.map_road_type.road_typeid
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setRoadTypeid(Integer roadTypeid) {
        this.roadTypeid = roadTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_type.road_name
     *
     * @return the value of map.map_road_type.road_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public String getRoadName() {
        return roadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_type.road_name
     *
     * @param roadName the value for map.map_road_type.road_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setRoadName(String roadName) {
        this.roadName = roadName == null ? null : roadName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_type.memo
     *
     * @return the value of map.map_road_type.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_type.memo
     *
     * @param memo the value for map.map_road_type.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}