package com.you07.map.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.vividsolutions.jts.geom.Geometry;
import com.you07.util.fastjson.GeometrySerializer;

public class MapRoutePolylineVerticesPgr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_route_polyline_vertices_pgr.id
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_route_polyline_vertices_pgr.cnt
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    private Integer cnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_route_polyline_vertices_pgr.chk
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    private Integer chk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_route_polyline_vertices_pgr.ein
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    private Integer ein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_route_polyline_vertices_pgr.eout
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    private Integer eout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_route_polyline_vertices_pgr.the_geom
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    @JSONField(serializeUsing = GeometrySerializer.class)
    private Geometry theGeom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_route_polyline_vertices_pgr.id
     *
     * @return the value of map.map_route_polyline_vertices_pgr.id
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_route_polyline_vertices_pgr.id
     *
     * @param id the value for map.map_route_polyline_vertices_pgr.id
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_route_polyline_vertices_pgr.cnt
     *
     * @return the value of map.map_route_polyline_vertices_pgr.cnt
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public Integer getCnt() {
        return cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_route_polyline_vertices_pgr.cnt
     *
     * @param cnt the value for map.map_route_polyline_vertices_pgr.cnt
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public void setCnt(Integer cnt) {
        this.cnt = cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_route_polyline_vertices_pgr.chk
     *
     * @return the value of map.map_route_polyline_vertices_pgr.chk
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public Integer getChk() {
        return chk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_route_polyline_vertices_pgr.chk
     *
     * @param chk the value for map.map_route_polyline_vertices_pgr.chk
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public void setChk(Integer chk) {
        this.chk = chk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_route_polyline_vertices_pgr.ein
     *
     * @return the value of map.map_route_polyline_vertices_pgr.ein
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public Integer getEin() {
        return ein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_route_polyline_vertices_pgr.ein
     *
     * @param ein the value for map.map_route_polyline_vertices_pgr.ein
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public void setEin(Integer ein) {
        this.ein = ein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_route_polyline_vertices_pgr.eout
     *
     * @return the value of map.map_route_polyline_vertices_pgr.eout
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public Integer getEout() {
        return eout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_route_polyline_vertices_pgr.eout
     *
     * @param eout the value for map.map_route_polyline_vertices_pgr.eout
     *
     * @mbg.generated Tue Dec 19 13:42:31 CST 2017
     */
    public void setEout(Integer eout) {
        this.eout = eout;
    }

    public Geometry getTheGeom() {
        return theGeom;
    }

    public void setTheGeom(Geometry theGeom) {
        this.theGeom = theGeom;
    }
}