package com.you07.map.model;

import com.alibaba.fastjson.annotation.JSONField;

public class MapRoadAttribute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.roadattr_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Integer roadattrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.pave_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @JSONField(serialize = false)
    private Integer paveId;

    private String pavementType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.plan_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @JSONField(serialize = false)
    private Integer planId;

    private String plan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.walkauth
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Integer walkauth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.carauth
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Integer carauth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.max_speed
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Float maxSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.is_single
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Boolean isSingle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.width
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Float width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.slope
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Float slope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.is_bridge
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Boolean isBridge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_attribute.road_typeid
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    @JSONField(serialize = false)
    private Integer roadTypeid;
    //道路类型
    private String edgeType;

    public String getPavementType() {
        return pavementType;
    }

    public void setPavementType(String pavementType) {
        this.pavementType = pavementType;
    }

    public String getPlan() {
        return plan;
    }

    public void setPlan(String plan) {
        this.plan = plan;
    }

    public String getEdgeType() {
        return edgeType;
    }

    public void setEdgeType(String edgeType) {
        this.edgeType = edgeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.roadattr_id
     *
     * @return the value of map.map_road_attribute.roadattr_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getRoadattrId() {
        return roadattrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.roadattr_id
     *
     * @param roadattrId the value for map.map_road_attribute.roadattr_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setRoadattrId(Integer roadattrId) {
        this.roadattrId = roadattrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.pave_id
     *
     * @return the value of map.map_road_attribute.pave_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getPaveId() {
        return paveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.pave_id
     *
     * @param paveId the value for map.map_road_attribute.pave_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setPaveId(Integer paveId) {
        this.paveId = paveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.plan_id
     *
     * @return the value of map.map_road_attribute.plan_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.plan_id
     *
     * @param planId the value for map.map_road_attribute.plan_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.walkauth
     *
     * @return the value of map.map_road_attribute.walkauth
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getWalkauth() {
        return walkauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.walkauth
     *
     * @param walkauth the value for map.map_road_attribute.walkauth
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setWalkauth(Integer walkauth) {
        this.walkauth = walkauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.carauth
     *
     * @return the value of map.map_road_attribute.carauth
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getCarauth() {
        return carauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.carauth
     *
     * @param carauth the value for map.map_road_attribute.carauth
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setCarauth(Integer carauth) {
        this.carauth = carauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.max_speed
     *
     * @return the value of map.map_road_attribute.max_speed
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Float getMaxSpeed() {
        return maxSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.max_speed
     *
     * @param maxSpeed the value for map.map_road_attribute.max_speed
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setMaxSpeed(Float maxSpeed) {
        this.maxSpeed = maxSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.is_single
     *
     * @return the value of map.map_road_attribute.is_single
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Boolean getIsSingle() {
        return isSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.is_single
     *
     * @param isSingle the value for map.map_road_attribute.is_single
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setIsSingle(Boolean isSingle) {
        this.isSingle = isSingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.width
     *
     * @return the value of map.map_road_attribute.width
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Float getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.width
     *
     * @param width the value for map.map_road_attribute.width
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setWidth(Float width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.slope
     *
     * @return the value of map.map_road_attribute.slope
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Float getSlope() {
        return slope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.slope
     *
     * @param slope the value for map.map_road_attribute.slope
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setSlope(Float slope) {
        this.slope = slope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.is_bridge
     *
     * @return the value of map.map_road_attribute.is_bridge
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Boolean getIsBridge() {
        return isBridge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.is_bridge
     *
     * @param isBridge the value for map.map_road_attribute.is_bridge
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setIsBridge(Boolean isBridge) {
        this.isBridge = isBridge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_attribute.road_typeid
     *
     * @return the value of map.map_road_attribute.road_typeid
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getRoadTypeid() {
        return roadTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_attribute.road_typeid
     *
     * @param roadTypeid the value for map.map_road_attribute.road_typeid
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setRoadTypeid(Integer roadTypeid) {
        this.roadTypeid = roadTypeid;
    }
}