package com.you07.map.model;

public class MapRoadPavementType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_pavement_type.pave_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Integer paveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_pavement_type.pave_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private String paveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_pavement_type.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_pavement_type.pave_id
     *
     * @return the value of map.map_road_pavement_type.pave_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getPaveId() {
        return paveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_pavement_type.pave_id
     *
     * @param paveId the value for map.map_road_pavement_type.pave_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setPaveId(Integer paveId) {
        this.paveId = paveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_pavement_type.pave_name
     *
     * @return the value of map.map_road_pavement_type.pave_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public String getPaveName() {
        return paveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_pavement_type.pave_name
     *
     * @param paveName the value for map.map_road_pavement_type.pave_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setPaveName(String paveName) {
        this.paveName = paveName == null ? null : paveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_pavement_type.memo
     *
     * @return the value of map.map_road_pavement_type.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_pavement_type.memo
     *
     * @param memo the value for map.map_road_pavement_type.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}