package com.you07.map.model;

public class MapRoadPlaneness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_planeness.plan_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private Integer planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_planeness.plan_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private String planName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.map_road_planeness.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_planeness.plan_id
     *
     * @return the value of map.map_road_planeness.plan_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_planeness.plan_id
     *
     * @param planId the value for map.map_road_planeness.plan_id
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_planeness.plan_name
     *
     * @return the value of map.map_road_planeness.plan_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_planeness.plan_name
     *
     * @param planName the value for map.map_road_planeness.plan_name
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.map_road_planeness.memo
     *
     * @return the value of map.map_road_planeness.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.map_road_planeness.memo
     *
     * @param memo the value for map.map_road_planeness.memo
     *
     * @mbg.generated Tue Dec 19 21:15:19 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}